name: flutter-version-number
description: "Reads the version number and build number from pubspec.yaml"
author: NiklasLehnfeld
branding:
  icon: "archive"
  color: "green"
inputs:
  file-path:
    description: "Path to your pubspec.yaml. Default is ./pubspec.yaml"
    required: false
    default: "./pubspec.yaml"
outputs:
  version-number:
    description: "Version number"
    value: ${{ steps.read-yaml.outputs.version-number }}
  build-number:
    description: "Build number"
    value: ${{ steps.read-yaml.outputs.build-number }}
runs:
  using: "composite"
  steps:
    - id: read-yaml
      run: |
        VERSION=`cat ${{inputs.file-path}} | grep -m 1 -o 'version:[^:]*' | cut -f2 -d":" | xargs`
        VERSION_NUMBER=`echo $VERSION | cut -d'+' -f1`
        BUILD_NUMBER=`echo $VERSION | cut -d'+' -f2`
        echo "version-number=$VERSION_NUMBER" >> $GITHUB_OUTPUT
        echo "build-number=$BUILD_NUMBER" >> $GITHUB_OUTPUT
      shell: bash
